stages:
  - build
  - deploy

build_image:
  variables: 
    APP_NAME: api
  stage: build
  image: docker
  services:
  - docker:dind
  script:
    - docker build -t $CI_COMMIT_SHORT_SHA .
    - docker login registry.pebblo.org --username=pebbloci --password=$DOCKER_REPO_PASSWORD
    - docker tag $CI_COMMIT_SHORT_SHA registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}
    - docker push registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}
  only:
    - master
    - develop

deploy_dev:
  stage: deploy
  image: debian:jessie-slim
  variables: 
    APP_NAME: api
    APP_INTERNAL_PORT: 3000
    APP_EXTERNAL_PORT: 8041
    CONTAINER_NAME: pebblo.org.api.${CI_COMMIT_REF_SLUG}
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AZURE_PROD_SSHKEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    # log into Docker registry
    - ssh pebbloci@$AZURE_PROD_IP "docker login registry.pebblo.org --username=pebbloci --password=$DOCKER_REPO_PASSWORD"
    # Remove image and stop container.
    - ssh pebbloci@$AZURE_PROD_IP "docker rmi registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker pull registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker stop $CONTAINER_NAME" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker rm $CONTAINER_NAME" || true
    # start new container
    - ssh pebbloci@$AZURE_PROD_IP "docker run --restart unless-stopped --name $CONTAINER_NAME -e NODE_ENV=production -e db_host=$DATABASE_IP -e db_name=$DATABASE_NAME -e db_password=$DATABASE_PASSWORD -e db_username=$DATABASE_USERNAME -e jwt_secret=$JWT_TOKENSECRET -e MINIO_ENDPOINT=$EUW_MINIO_IP -e MINIO_ACCESSKEY=$EUW_MINIO_ACCESS -e MINIO_SECRETKEY=$EUW_MINIO_SECRET -p $APP_EXTERNAL_PORT:$APP_INTERNAL_PORT -d registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}"  
  only:
    - develop

deploy:
  stage: deploy
  image: debian:jessie-slim
  variables: 
    APP_NAME: api
    APP_INTERNAL_PORT: 3000
    APP_EXTERNAL_PORT: 8040
    CONTAINER_NAME: pebblo.org.api.${CI_COMMIT_REF_SLUG}
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AZURE_PROD_SSHKEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    # log into Docker registry
    - ssh pebbloci@$AZURE_PROD_IP "docker login registry.pebblo.org --username=pebbloci --password=$DOCKER_REPO_PASSWORD"
    # Remove image and stop container.
    - ssh pebbloci@$AZURE_PROD_IP "docker rmi registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker pull registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker stop $CONTAINER_NAME" || true
    - ssh pebbloci@$AZURE_PROD_IP "docker rm $CONTAINER_NAME" || true
    # start new container
    - ssh pebbloci@$AZURE_PROD_IP "docker run --restart unless-stopped --name $CONTAINER_NAME -e NODE_ENV=production -e db_host=$DATABASE_IP -e db_name=$DATABASE_NAME -e db_password=$DATABASE_PASSWORD -e db_username=$DATABASE_USERNAME -e jwt_secret=$JWT_TOKENSECRET -e MINIO_ENDPOINT=$EUW_MINIO_IP -e MINIO_ACCESSKEY=$EUW_MINIO_ACCESS -e MINIO_SECRETKEY=$EUW_MINIO_SECRET -p $APP_EXTERNAL_PORT:$APP_INTERNAL_PORT -d registry.pebblo.org/$APP_NAME:${CI_COMMIT_REF_SLUG}"
  only:
    - master